{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.restapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm.restapi.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.restapi.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "slurm.restapi.selectorLabels" . | nindent 4 }}
  {{- with .Values.restapi.service }}
  {{- toYaml . | nindent 2 }}
  {{- end }}{{- /* with .Values.restapi.service */}}
  ports:
    - name: slurmrestd
      protocol: TCP
      port: {{ .Values.restapi.servicePort }}
      targetPort: {{ include "slurm.restapi.port" . }}
      {{- if eq (.Values.restapi.service.type | default "ClusterIP" | lower) ("NodePort" | lower) }}
      nodePort: {{ .Values.restapi.serviceNodePort }}
      {{- end }}{{- /* if eq (.Values.restapi.service.type | default "ClusterIP" | lower) ("NodePort" | lower) */}}
{{- end }}{{- /* if .Values.restapi.enabled */}}
