{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm.controller.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.controller.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "slurm.controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: slurmctld
      protocol: TCP
      port: {{ .Values.controller.servicePort }}
      targetPort: {{ include "slurm.controller.port" . }}
      {{- if eq (.Values.controller.service.type | default "ClusterIP" | lower) ("NodePort" | lower) }}
      nodePort: {{ .Values.controller.serviceNodePort }}
      {{- end }}{{- /* if eq (.Values.controller.service.type | default "ClusterIP" | lower) ("NodePort" | lower) */}}
