{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $localOperator := and (.Values.debug.enabled) (.Values.debug.localOperator) -}}
apiVersion: slinky.slurm.net/v1alpha1
kind: Cluster
metadata:
  name: {{ include "slurm.cluster.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.cluster.labels" . | nindent 4 }}
spec:
  {{- if $localOperator }}
  server: {{ printf "http://localhost:%s" (include "slurm.restapi.port" .) }}
  {{- else }}{{- /* if $localOperator */}}
  server: {{ printf "http://%s.%s:%s" (include "slurm.restapi.name" .) (include "slurm.namespace" .) (include "slurm.restapi.port" .) }}
  {{- end }}{{- /* if $localOperator */}}
  token:
    secretRef: {{ include "slurm.cluster.secretName" . }}
