{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slurm.cluster.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "slurm.cluster.name" . }}
  namespace: {{ include "slurm.namespace" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - secrets/finalizers
  verbs:
  - create
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "slurm.cluster.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "slurm.cluster.name" . }}
  namespace: {{ include "slurm.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "slurm.cluster.name" . }}
